/*
 * DO NOT EDIT -- generated by the Makefile rule have_strlcat.h
 */


#if !defined(INCLUDE_STRLCAT_H)
#define INCLUDE_STRLCAT_H


/* do we have the strlcat() function? */
#define HAVE_STRLCAT /* yes - use libc function */


#endif
