/*
 * DO NOT EDIT -- generated by the Makefile rule have_strlcpy.h
 */


#if !defined(INCLUDE_STRLCPY_H)
#define INCLUDE_STRLCPY_H


/* do we have the strlcpy() function? */
#define HAVE_STRLCPY /* yes - use libc function */


#endif
