/*
 * DO NOT EDIT -- generated by the Makefile rule modern_curses.h
 */


#if !defined(INCLUDE_MODERN_CURSES_H)
#define INCLUDE_MODERN_CURSES_H


/* do have modern new curses ? */
#include <ncurses.h> /* yes, using new curses */

#define MODERN_CUESES NEW_CURSES


#endif
