#!/usr/bin/env bash
#
# hplot: Rog-O-Matic XIV (CMU) Thu Jul  3 16:35:59 1986 - mlm
# Copyright (C) 1985 by A. Appel, G. Jacobson, L. Hamey, and M. Mauldin
#
# Bug fixes by: Landon Curt Noll (chongo was here) ^oo^
#

export ROGOMATIC="rogomatic"
if [[ -x ./rogomatic ]]; then
    ROGOMATIC="./rogomatic"
fi
if [[ ! -x $ROGOMATIC ]]; then
    echo "$0: ERROR: rogomatic executable not found" 1>&2
    exit 1
fi

export HISTPLOT="histplot"
if [[ -x ./histplot ]]; then
    HISTPLOT="./histplot"
fi
if [[ ! -x $HISTPLOT ]]; then
    echo "$0: ERROR: histplot executable not found" 1>&2
    exit 2
fi

"$ROGOMATIC" -s | \
    "$HISTPLOT" "$@"
